spring.application.name=taskmanagement
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagement_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Harshytha@776
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.filter.order=10
spring.jpa.open-in-view=false